name: Deploy to Server

on:
  push:
    branches:
      - main # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" << 'EOF'
            cd /www/wwwroot/frontend
            git pull origin main  # 拉取最新代码
            npm install  # 安装依赖
            rm -f /www/wwwroot/frontend/dist/.user.ini
            npm run build  # 构建项目
          EOF
